import type { Metadata } from "next"
import { Bagel_Fat_One, DM_Sans } from "next/font/google"
import "./globals.css"

const bagel = Bagel_Fat_One({
     weight: "400",
     variable: "--font-bagel",
     subsets: ["latin"],
})

const dm_sans = DM_Sans({
     variable: "--font-geist-mono",
     subsets: ["latin"],
})

export const metadata: Metadata = {
     title: "Create Next App",
     description: "Generated by create next app",
}

export default function RootLayout({ children }: LayoutProps<"/">) {
     return (
          <html lang="fr" className={`${bagel.variable} ${dm_sans.variable} font-dm h-full antialiased`}>
               <body>{children}</body>
          </html>
     )
}
